apiVersion: v1
kind: Service
metadata:
  name: sudoku-solver-service
spec:
  selector:
    app: sudoku-solver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer  
